"""
Report Agent.
Synthesises the compliance analysis and risk assessment into a
professional executive-grade audit report with an executive summary
and structured recommendations.

The executive summary is generated deterministically from the structured
compliance_analysis and risk_assessment data without an additional LLM call.
This eliminates one blocking Ollama round-trip (~30-50s) and ensures the
workflow completes within the frontend timeout window.
"""

import time
from datetime import datetime, timezone
from typing import Any

from app.agents.base import BaseAgent
from app.core.logging import get_logger

logger = get_logger(__name__)

# Risk level descriptors for use in the executive summary
_RISK_DESCRIPTORS = {
    "High": (
        "The audit has identified a HIGH level of compliance risk. "
        "Immediate intervention is required. Several critical or high-severity gaps were found "
        "that expose the organisation to regulatory enforcement action, financial penalties, "
        "and reputational damage if not addressed within the immediate remediation window."
    ),
    "Medium": (
        "The audit has identified a MEDIUM level of compliance risk. "
        "While the organisation maintains partial alignment with the applicable regulatory framework, "
        "material gaps require structured remediation within the short-to-medium term. "
        "Failure to address these findings may escalate the risk profile in subsequent audit cycles."
    ),
    "Low": (
        "The audit has identified a LOW level of compliance risk. "
        "The organisation demonstrates strong alignment with the applicable regulatory framework. "
        "Minor deficiencies identified should be addressed through normal policy maintenance cycles "
        "to sustain the current compliance posture."
    ),
}


def _build_executive_summary(
    compliance_analysis: dict,
    risk_assessment: dict,
) -> str:
    """
    Compose a structured executive summary from the compliance and risk data
    without making any LLM call. Uses deterministic templates enriched with
    actual audit metrics.
    """
    risk_level = risk_assessment.get("risk_level", "Unknown")
    score = risk_assessment.get("overall_score", 0)
    violation_count = compliance_analysis.get("violation_count", 0)
    issues = compliance_analysis.get("issues", [])
    recommendations = compliance_analysis.get("recommendations", [])
    audit_timestamp = compliance_analysis.get(
        "audit_timestamp",
        datetime.now(tz=timezone.utc).isoformat(),
    )
    auditor = compliance_analysis.get("auditor", "Compliance AI Platform")

    risk_descriptor = _RISK_DESCRIPTORS.get(
        risk_level,
        f"The audit has identified a {risk_level} level of compliance risk. "
        f"The findings should be reviewed and addressed according to their severity classification.",
    )

    # Top issues — capped at 5 for readability
    top_issues = issues[:5]
    if top_issues:
        issues_text = " ".join(
            f"({i+1}) {issue.strip().rstrip('.')}."
            for i, issue in enumerate(top_issues)
        )
        issues_paragraph = (
            f"The primary findings include the following: {issues_text}"
        )
    else:
        issues_paragraph = (
            "No specific policy violations were identified during this audit cycle."
        )

    rec_count = len(recommendations)
    rec_text = (
        f"A total of {rec_count} remediation recommendation{'s have' if rec_count != 1 else ' has'} "
        f"been issued, prioritised by severity classification. "
        f"The organisation is advised to act on critical and high-severity findings within the "
        f"immediate action window as specified in the accompanying Mitigation Roadmap."
        if rec_count > 0
        else "No specific remediation recommendations were generated for this cycle."
    )

    summary = (
        f"EXECUTIVE SUMMARY — ENTERPRISE COMPLIANCE AUDIT\n"
        f"Audit Date: {audit_timestamp} | Auditor: {auditor}\n\n"
        f"Overall Compliance Score: {score}/100 | Risk Level: {risk_level} | "
        f"Total Violations Identified: {violation_count}\n\n"
        f"{risk_descriptor}\n\n"
        f"{issues_paragraph}\n\n"
        f"{rec_text}\n\n"
        f"This report should be reviewed by the Chief Compliance Officer and relevant "
        f"business unit owners. All findings and recommendations contained herein are "
        f"generated by the Enterprise Compliance AI Platform and should be validated "
        f"against the applicable regulatory instruments before final action is taken."
    )
    return summary


class ReportAgent(BaseAgent):
    """
    Produces the final deliverable: a structured audit report
    containing an executive summary, detailed findings, and
    a prioritised recommendation list. No LLM calls are made —
    all data is synthesised from the upstream agent outputs.
    """

    @property
    def name(self) -> str:
        return "ReportAgent"

    def run(self, context: dict[str, Any]) -> dict[str, Any]:
        """
        Args:
            context: Must contain:
                - compliance_analysis: dict (from ComplianceAgent)
                - risk_assessment: dict (from RiskAgent)

        Returns:
            final_report: dict with executive_summary, structured_findings,
                          recommendations, metadata
        """
        t_start = time.monotonic()
        compliance_analysis: dict = context.get("compliance_analysis", {})
        risk_assessment: dict = context.get("risk_assessment", {})

        if not compliance_analysis:
            return {"error": "ReportAgent requires compliance_analysis in context."}
        if not risk_assessment:
            return {"error": "ReportAgent requires risk_assessment in context."}

        executive_summary = _build_executive_summary(compliance_analysis, risk_assessment)
        structured_findings = self._structure_findings(compliance_analysis, risk_assessment)

        final_report = {
            "executive_summary": executive_summary,
            "structured_findings": structured_findings,
            "risk_level": risk_assessment.get("risk_level", "Unknown"),
            "compliance_score": risk_assessment.get("overall_score", 0),
            "total_violations": compliance_analysis.get("violation_count", 0),
            "issues": compliance_analysis.get("issues", []),
            "recommendations": compliance_analysis.get("recommendations", []),
            "mitigation_roadmap": risk_assessment.get("mitigation_roadmap", ""),
            "audit_timestamp": compliance_analysis.get("audit_timestamp", ""),
            "auditor": compliance_analysis.get("auditor", "Compliance AI Platform"),
        }

        elapsed = time.monotonic() - t_start
        logger.info(
            f"{self.name}: final report produced in {elapsed:.2f}s — "
            f"risk={final_report['risk_level']} "
            f"score={final_report['compliance_score']}"
        )
        return {"final_report": final_report}

    def _structure_findings(
        self,
        compliance_analysis: dict,
        risk_assessment: dict,
    ) -> list[dict]:
        """
        Combine per-issue severity with the issue text into a
        structured findings list for the report viewer.
        """
        per_issue = risk_assessment.get("per_issue_severity", [])
        recommendations = compliance_analysis.get("recommendations", [])

        findings = []
        for item in per_issue:
            idx = item.get("index", 0)
            findings.append(
                {
                    "finding_number": idx + 1,
                    "description": item.get("issue", ""),
                    "severity": item.get("severity", "medium"),
                    "recommendation": (
                        recommendations[idx]
                        if idx < len(recommendations)
                        else "Review and remediate."
                    ),
                }
            )
        return findings
